### PR TITLE
[Fix] Get correct query sizes when iterating in simd mode

### LINKED ISSUE #134: searchn on short reads causes wrong qlen results
Hello there,

We have aligned a nucleotide database and are running `searchn` (currently v1.9.5) on some input FASTA that have short reads; sometimes these can cause odd results around the outputs of `qlen`/`qend`:

Test no.1 (33bp test, by itself) (`searchn` run with `--output-columns "std qlen slen"`):
```
>Test33bp
TGCGCCTGGACGCCATCACCGGCCCCGAGGAGG
```
Results (OK):
```
Test33bp  AE004091.2  100.00  33  0  0  33  1  1240784  1240816  3e-09  60.8  33  6264404
```

Test no.2 (33bp test with another 20bp one before it):
```
>Test20bp
GGCTTCGGCACAGCAATTGA
>Test33bp
TGCGCCTGGACGCCATCACCGGCCCCGAGGAGG
```

Results (`qend` underflowed(?) -- `qstart` appears to be "leaked" from the previous query (20)):
```
Test33bp  AE004091.2  100.00  33  0  0  20  4294967284  1240784  1240816  1e-09  60.8  20  6264404
```

Pairwise results:
```
> AE004091.2                                                                                                                                                                                                       
Length=6264404                                                                                                                                                                                                     
                                                                                                                                                                                                                   
 Score =  60.8 bits (66), Expect =  3e-09                                                                                                                                                                          
 Identities = 33/33 (100%), Gaps = 0/33 (0%)                                                                                                                                                                       
 Strand=Minus/Minus                                                                                                                                                                                                
                                                                                                                                                                                                                   
Query  0           CCTCCTCGGGGCCGGTGATGGCGTCCAGGCGCA  -32                                                                                                                                                          
                   |||||||||||||||||||||||||||||||||                                                                                                                                                               
Sbjct  1240784     CCTCCTCGGGGCCGGTGATGGCGTCCAGGCGCA  1240816
```

---

This was first observed in a test set that varied in query lengths from 16-50bps). The `qlen` of this 33bp test had a `qend` greater than the actual length of the original query input (33bps).

```
Test33bp  AE004091.2  100.00  33  0  0  48  16  1240784  1240816  8e-09  60.8  48  6264404 208964                                                                 
```
[when reversing]
qstart = 16
qend = 48 (???)
original query length = 33

---

Are there requirements around input query length when performing `searchn`, or other settings we should be looking for to tweak? It still appears that there is still a leak somewhere...

EDIT: as I was typing this issue you opened (https://github.com/seqan/lambda/pull/133). Feel free to close this issue if this is related. :)

### PR DESCRIPTION
**Pull request by sarahet**
Fixes #134

### CODE REVIEW

**Comment by sarahet** [comment]
gcc7 build fails because it doesn't find some include paths (which I haven't touched). Is that expected? Clang seems to have a problem detecting the compiler.

**Comment by h-2** [comment]
I guess some things in travis are just outdated. Have you worked with travis before? Can you try to update the `.travis.yml` ? SeqAn2 and SeqAn3 have working configs...

**Comment by sarahet** [comment]
Travis builds are fixed now :tada:

**Comment by h-2** [comment]
LGTM! Thanks for the PR.

**Pull request merged**
