### PR TITLE
Update lambda3 from master

### PR DESCRIPTION
**Pull request by sarahet**
Finally :sparkles:

### CODE REVIEW

**Comment by h-2** [comment]
Ok! And the macOS build on lambda3 is broken anyway, right?

**Comment by sarahet** [comment]
> Ok! And the macOS build on lambda3 is broken anyway, right?

I think so, at least we ignored it for your last PR as well. But maybe we should find out why at some point ..

**Comment by h-2** [comment]
> But maybe we should find out why at some point ..

It's likely the same travis-brokennes that also affected the master branch! Feel free to submit a PR now that you figured it out for master :wink:

**Comment by sarahet** [comment]
> > But maybe we should find out why at some point ..
> 
> It's likely the same travis-brokennes that also affected the master branch! Feel free to submit a PR now that you figured it out for master

Although it's a different error message, but I will figure it out

**Pull request merged**
