### PR TITLE
[fix] workaround bug in cereal

### PR DESCRIPTION
**Pull request by h-2**
Can you check the (de)serialisation performance with this branch?

### CODE REVIEW

**Comment by sarahet** [comment]
Clang format is failing :slightly_smiling_face:

**Comment by sarahet** [comment]
Index loading time:

This branch - 12.558s
This branch with https://github.com/seqan/lambda/pull/191 - 9.899s
@SGSSGene's workaround and https://github.com/seqan/lambda/pull/191 - 10.4s

**Review by sarahet — APPROVED** [review]
LGTM

**Comment by h-2** [comment]
Thanks for evaluating it!

**Comment by h-2** [comment]
This is the upstream issue: https://github.com/USCiLab/cereal/pull/769

**Pull request merged**
